msg:
  prefix: "&3[&4GottaGras&5-&6Core&7]&8 "
  no-perm: "Impossible d'executer cette commande"
  teleport: "Teleportation reussite"
  impossible: "Action impossible !"
hub:
  world: world
  x: 0.5
  y: 121
  z: 0.5