msg:
  motd: "&3[&4GottaGras&5-&6Core&7]&8 1.8 => 1.8.9\n&6Mini-jeux:&7 UHC [En dev], PvPSwap [Bientot]"
  op-join: "Le grand &6<player> &8nous a rejoint"
  op-quit: "Aie, aie, aie, &6<player> &8viens de nous quitter"
  player-join: "Slt &6<player>"
  player-quit: "Ciao &6<player>"
  prefix: "&3[&4GottaGras&5-&6Core&7]&8 "
  no-perm: "Impossible d'executer cette commande"
  teleport: "Teleportation reussite"
  impossible: "Action impossible !"
  revive: "viens d'etre revive"
hub:
  world: world
  x: 0.5
  y: 121
  z: 0.5
uhc:
  time:
    invincible: 30
    pvp: 60
    border: 120
    meetup: 240
  scenario:
    nether: true
    final-heal: true
    alltreedrop: true
    alltreedrop-rate: 5
    fireless: true
    cutclean: true
    hasteyboys: true