msg:
  motd: "&3[&4GottaGras&5-&6Core&7]&8 1.8 => 1.8.9\n&6Mini-jeux:&7 UHC, Meetup et d'autre qui arrive"
  op-join: "Le grand &6<player> &8nous a rejoint"
  op-quit: "Aie, aie, aie, &6<player> &8vient de nous quitter"
  player-join: "Slt &6<player>"
  player-quit: "Ciao &6<player>"
  prefix: "&3[&4GottaGras&5-&6Core&7]&8 "
  no-perm: "Impossible d'executer cette commande"
  teleport: "Teleportation reussite"
  impossible: "Action impossible !"
  revive: "vient d'etre revive"
hub:
  world: world
  x: 0.5
  y: 121
  z: 0.5
jump:
  world: world
  x: 56.5
  y: 18
  z: -22.5
  xp: 63
  xn: -21
  yp: 31
  yn: 0
  zp: 87
  zn: -30
uhc:
  time:
    invincible: 30
    pvp: 1200
    border: 3600
    meetup: 4800
  scenario:
    nether: true
    final-heal: true
    alltreedrop: true
    alltreedrop-rate: 5
    fireless: true
    cutclean: true
    hasteyboys: true
    netherboat: false